
# Create Smart LayoutLog
POST http://localhost:7001/api/smartLayoutLog/create
Content-Type: application/json

{
  "data": {
    "prompt": "show me list of dior store",
    "type": "bar"
  }
}

###
# Create SmartLayout
POST http://localhost:7001/api/smartLayout/create
Content-Type: application/json

{
  "data": {
    "prompt": "show me list of dior store",
    "type": "bar",
    "smartLayoutLogId": "2",
    "userId": "1"
  }
}

###
GET http://localhost:7001
Accept: application/json

###
